# Generated by Django 5.2.4 on 2025-07-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_login_provider',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='refresh_token',
        ),
    ]
