# Generated by Django 5.2.4 on 2025-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(max_length=50),
        ),
    ]
