# Generated by Django 5.2.4 on 2025-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
